name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Show Go version
        run: go version

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Run standalone analyzer
        run: go run ./cmd/loglint ./...

      - name: Add Go bin to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.8

      - name: Build custom golangci-lint binary
        run: golangci-lint custom -v

      - name: Run custom golangci-lint
        run: ./custom-gcl run ./...
